setzer poke

diff --git a/libexec/setzer/setzer-latest b/libexec/setzer/setzer-latest
--- a/libexec/setzer/setzer-latest
+++ b/libexec/setzer/setzer-latest
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
 ### setzer-latest -- Latest valid price messages for a pair
 ### Usage: setzer latest <pair> [address]
-###
-### TODO
-### Filter invalid authors if an oracle is provided
 set -e
 [ $# -gt 0 ] || setzer --bad-usage "$0"
 pair=$(setzer --pair "$1")
+[[ "$2" ]] && oracle=$(seth --to-address "$2")
 
 previous()
 {
@@ -26,13 +24,17 @@ valid()
     if [[ ! $authors = *"$a"* ]]
     then
       authors+=$a
-      echo "$1" | jq '.'
-    else
-      echo "$1" | jq '.'
+      setzer --valid-message "$1" "$oracle"
     fi
 }
 
-msg=$(head -n 1 <(setzer ssb latest "${pair^^}" | jq -c '.|.value'))
-key=$(echo "$msg" | jq -r '.previous')
-valid "$msg"
-previous 2 "$key"
+msg=$(head -n 1 <(setzer ssb messages "${pair^^}" | jq -c '.|.value'))
+if [[ -n "$msg" ]]
+then
+  key=$(echo "$msg" | jq -r '.previous')
+  valid "$msg"
+  previous 2 "$key"
+else
+  echo >&2 "Error: no valid $pair prices"
+  exit 1
+fi
diff --git a/libexec/setzer/setzer-poke b/libexec/setzer/setzer-poke
--- a/libexec/setzer/setzer-poke
+++ b/libexec/setzer/setzer-poke
@@ -1,29 +1,43 @@
 #!/usr/bin/env bash
 ### setzer-poke -- Poke a medianizer with latest prices
 ### Usage: setzer poke <address>
-set -ex
+set -e
 [ $# -gt 0 ] || setzer --bad-usage "$0"
 oracle=$(seth --to-address "$1")
 pair=$(seth call "$oracle" 'wat()')
 pair=$(setzer --to-ascii "$pair")
 pair=$(setzer --pair "$pair")
 
-latest=$(setzer latest "$pair" | jq -s '.')
-length=$(echo "$latest" | jq '.|length')
+msgs=$(setzer latest "$pair" | jq -s '.|sort_by(.price)')
+size=$(echo "$msgs" | jq '.|length')
 
-if [[ $length -lt "$SETZER_QUORUM" ]]
+if [[ $size -lt "$SETZER_QUORUM" ]]
 then
-  echo >&2 "Error: insufficient price data ($length of $SETZER_QUORUM)"
+  echo >&2 "Error: insufficient price data ($size of $SETZER_QUORUM)"
   exit 1
 fi
 
-while read -r sign price timestamp; do
-  ps+=$price
-  ts+=$timestamp
-  vs+="${sign:0:64}"
-  rs+="${sign:64:64}"
-  ss+="$(seth --to-word "0x${sign:128:2}")"
-done <<<"$(echo "$latest" | jq -r '.[] | [.content.sig, .content.data.price, .content.data.timestamp] | @tsv')"
+age=$(seth --to-dec "$(seth call "$oracle" 'age()')")
 
-sig="poke(uint256[] memory,uint256[] memory,uint8[] memory,bytes32[] memory,bytes32[] memory)"
-seth send "$oracle" "$sig" "$ps" "$ts" "$vs" "$rs" "$ss"
+era()
+{
+  if [[ $age -gt "$(seth --to-dec "$1")" ]]
+  then
+    echo >&2 "Error: oracle already poked: $(printf '%(%Y-%m-%d %H:%M:%S)T\n' "$age")"
+    exit 1
+  fi
+  echo "$1"
+}
+
+while read -r sig val timestamp; do
+  vals+=("$val")
+  eras+=("$(era "$timestamp")")
+  v__s+=("$(seth --to-word "0x${sig:130:2}")")
+  r__s+=("${sig:2:64}")
+  s__s+=("${sig:66:64}")
+done <<<"$(echo "$msgs" | jq -r '.[] | [.content.sig, .content.data.price, .content.data.timestamp] | @tsv')"
+
+IFS=","
+f="poke(uint256[] memory,uint256[] memory,uint8[] memory,bytes32[] memory,bytes32[] memory)"
+ETH_GAS=${ETH_GAS:-500000} seth send "$oracle" "$f" \
+  "[${vals[*]}]" "[${eras[*]}]" "[${v__s[*]}]" "[${r__s[*]}]" "[${s__s[*]}]"
